# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 23:31
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170406_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='posted',
            field=models.DateTimeField(verbose_name=b'"Publish" Date'),
        ),
    ]
