# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_side', models.CharField(choices=[(b'l', b'left'), (b'r', b'right')], max_length=1)),
                ('nav_pos', models.PositiveIntegerField()),
                ('nav_show', models.BooleanField(default=False)),
                ('nav_icon', models.CharField(max_length=64)),
                ('nav_heading', models.CharField(max_length=32)),
                ('page_heading', models.CharField(max_length=256)),
                ('page_body', models.TextField()),
                ('page_slug', models.SlugField(max_length=16)),
            ],
        ),
    ]
