# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('in_index', models.BooleanField(default=False)),
            ],
        ),
    ]
